# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  default: go build -o ./bin/ ./cmd/learn-go
  run: "go run ./cmd/learn-go"
  test: go test -v ./cmd/learn-go
  clean: rm -rf ./bin
